# Generated by Django 2.1.1 on 2019-07-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pods', models.BooleanField(default=True, verbose_name='Air pods')),
            ],
            options={
                'verbose_name': 'Iphone',
                'verbose_name_plural': 'Iphones',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('os', models.CharField(max_length=15, verbose_name='Операционная система')),
                ('sim', models.CharField(max_length=1, verbose_name='Количество SIM-карт')),
                ('memory', models.CharField(max_length=5, verbose_name='Объём оперативной памяти')),
                ('gps', models.BooleanField(default=False, verbose_name='GPS')),
                ('fmradio', models.BooleanField(default=False, verbose_name='FM-Радио')),
            ],
            options={
                'verbose_name': 'Смартфон',
                'verbose_name_plural': 'Смартфоны',
                'ordering': ['model', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
            options={
                'verbose_name': 'Samsungs',
                'verbose_name_plural': 'Samsung',
            },
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.BooleanField(default=False, verbose_name='Сканер отпечатка пальцев')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
            options={
                'verbose_name': 'Xiaomi',
                'verbose_name_plural': 'Xiaomis',
            },
        ),
        migrations.AddField(
            model_name='iphone',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='phones.Phone'),
        ),
    ]
