# Generated by Django 2.1.1 on 2019-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190704_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='student', to='school.Teacher', verbose_name='Учителя'),
        ),
    ]
